fix(multisite): update table prefix after blog switch
dimitriBouteille/wp-orm pull request #101
Opened 2024-12-18 09:31 UTC by rafaucau

2024-12-18 18:16 UTC, rafaucau commented
When I use:
```php
add_action('switch_blog', function () {
    $this->setTablePrefix($this->db->prefix);
});
```
This only works partially. It works correctly in the model's `getTable()` method, but then there's an error when executing the query: 
```
Fatal error: Uncaught Exception: Table 'wordpress.wp_2_wp_2_posts' doesn't exist in wp-orm/src/Orm/Database.php:395
```
I can't find the place that could be causing generation of a double prefix after executing the `setTablePrefix()` method. It's not the `table` method or other similar ones in the `Database` class.

I'll reset the entire instance:
```php
add_action('switch_blog', function () {
    self::$instance = null;
});
```
This works correctly.

2025-01-25 21:32 UTC, dimitriBouteille requested changes
Hi @rafaucau 

Thank you for your contribution!

I made 2 small feedbacks. Before validating the PR, I want to take the time to test and write some tests.

I hope to validate this RP in February for the `4.2.0`.

2025-01-25 21:32 UTC, dimitriBouteille commented on src/Orm/Database.php
> +    protected function addWordPresHooks(): void
```suggestion
    protected function addWordPressHooks(): void
```

2025-01-25 21:32 UTC, dimitriBouteille commented on src/Models/Multisite/Blog.php
> +    final public const  LAST_UPDATED = 'last_updated';
```suggestion
    final public const LAST_UPDATED = 'last_updated';
```

2025-02-28 18:59 UTC, rafaucau commented
Hey @dimitriBouteille, just checking in on this PR. Is there anything I can help with to move things forward?

2025-03-01 12:15 UTC, dimitriBouteille commented
Hi @rafaucau 

I am sorry for the long delay to validate this PR :(

Could you replace the `@property` by `@method` (set and get) as it is done for other models.

The objective is to maintain consistency with other models.

2025-03-01 13:29 UTC, rafaucau commented
@dimitriBouteille done

2025-03-01 18:48 UTC, merged

2025-03-01 18:50 UTC, dimitriBouteille commented
@rafaucau Thank you  for your contribution.

I’m looking to add some tests. The fix will be available in the next release [4.3.0](https://github.com/dimitriBouteille/wp-orm/milestone/11) :rock: